### ISSUE TITLE
Mistake in Readme.md

### ISSUE THREAD

**Issue by Stevemoretz** [LaraPKG/lumen-discovery#2]
Hi `composer require larapkg/lumen-discover` should be `composer require larapkg/lumen-discovery` indeed!

also
```
            "providers": [
                "Corcel\Laravel\CorcelServiceProvider"
            ]
```
should be 

```
            "providers": [
                "Corcel\\Laravel\\CorcelServiceProvider"
            ]
```

**Comment by ronappleton** [comment]
Hi @Stevemoretz thanks for this, @Somesh93 provided the fix for the require statement, I am at a loss though for the CorcelServiceProvider?

**Comment by ronappleton** [comment]
Hi again @Stevemoretz my apologies, I spotted it lol

**Comment by Stevemoretz** [comment]
Lol no problem thank you for this great package!
